### ISSUE TITLE
Implement libstd support

### ISSUE THREAD

**Issue by roblabla** [MegatonHammer/megaton-hammer#8]
libcore is fun, but libstd is more fun. Requires #7

**Comment by FenrirWolf** [comment]
Cargo might be an okay home for some components, but based on my experience with `ctru-rs` I'd argue that it's better to keep most of the std implementation as github dependencies. This is because libstd and everything else in the sysroot are effectively unversioned from a semver point of view, and Cargo inherently cares a lot about crate versions.

The details of sysroot components can and will change at the drop of a hat (especially when doing updates to new nightlies) and so you need the freedom to be able to change libstd and other components to match those changes without forcing the user to bump versions all the time. Ideally they should be able to just install a compatible nightly with rustup, clone a template project, and be off to the races.

**Comment by roblabla** [comment]
Done. Going to start issues for implementation subtasks.
